name: NetPeekSample
options:
  bundleIdPrefix: io.netpeek
  deploymentTarget:
    iOS: "16.0"

targets:
  NetPeekSample:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.netpeek.sample.ios
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        # Point to KMP-built frameworks
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(SRCROOT)/../netpeek-sdk/build/bin/iosSimulatorArm64/debugFramework $(SRCROOT)/../netpeek-ui/build/bin/iosSimulatorArm64/debugFramework
    info:
      path: Sources/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSupportsMultipleScenes: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    dependencies:
      - framework: ../netpeek-sdk/build/bin/iosSimulatorArm64/debugFramework/netpeek_sdk.framework
        embed: true
        codeSign: false
      - framework: ../netpeek-ui/build/bin/iosSimulatorArm64/debugFramework/netpeek_ui.framework
        embed: true
        codeSign: false
